// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGEBI.Persistence.Context;

#nullable disable

namespace SIGEBI.Persistence.Migrations
{
    [DbContext(typeof(SigebiDbContext))]
    [Migration("20260623220647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGEBI.Domain.Entities.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EntidadAfectada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntidadAfectadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Accion");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("Modulo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosAuditoria", "auditoria");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Autores", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Ejemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EstadoFisico")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecursoBibliograficoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("RecursoBibliograficoId");

                    b.ToTable("Ejemplares", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.HistorialEstadoEjemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EjemplarId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UsuarioResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.ToTable("HistorialEstadosEjemplar", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.RecursoAutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("RecursoBibliograficoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("RecursoBibliograficoId", "AutorId")
                        .IsUnique();

                    b.ToTable("RecursosAutores", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.RecursoBibliografico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Edicion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Editorial")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isbn")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("Isbn")
                        .IsUnique()
                        .HasFilter("[Isbn] IS NOT NULL");

                    b.HasIndex("Titulo");

                    b.ToTable("RecursosBibliograficos", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.RecursoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("RecursoBibliograficoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RecursoBibliograficoId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("RecursosCategorias", "catalogo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Configuracion.ParametroSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("ParametrosSistema", "configuracion");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Configuracion.PoliticaPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DiasDuracionPrestamo")
                        .HasColumnType("int");

                    b.Property<int>("DiasSuspensionPorDiaRetraso")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasReservaTemporal")
                        .HasColumnType("int");

                    b.Property<int>("MaximoPrestamosActivos")
                        .HasColumnType("int");

                    b.Property<bool>("PenalizaRetraso")
                        .HasColumnType("bit");

                    b.Property<bool>("PermitePrestamoConVencidos")
                        .HasColumnType("bit");

                    b.Property<int>("TipoMiembro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoMiembro")
                        .IsUnique();

                    b.ToTable("PoliticasPrestamo", "configuracion");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Notificaciones.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("EntidadReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntidadReferenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UsuarioDestinatarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaEnvio");

                    b.HasIndex("UsuarioDestinatarioId");

                    b.ToTable("Notificaciones", "notificaciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Penalizaciones.IncidenciaEjemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EjemplarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReportaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cerrada");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("Tipo");

                    b.HasIndex("UsuarioCierreId");

                    b.HasIndex("UsuarioReportaId");

                    b.ToTable("IncidenciasEjemplar", "penalizaciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Penalizaciones.Penalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DiasSuspension")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoResolucion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResolutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaFin");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioResolutorId");

                    b.ToTable("Penalizaciones", "penalizaciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasRetraso")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueTardia")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioBibliotecarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaDevolucion");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("UsuarioBibliotecarioId");

                    b.ToTable("Devoluciones", "prestamos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EjemplarId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimiteDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SolicitudPrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioBibliotecarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaLimiteDevolucion");

                    b.HasIndex("SolicitudPrestamoId");

                    b.HasIndex("UsuarioBibliotecarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos", "prestamos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.ReservaTemporal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EjemplarId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudPrestamoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaExpiracion");

                    b.HasIndex("SolicitudPrestamoId");

                    b.ToTable("ReservasTemporales", "prestamos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.SolicitudPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("EjemplarId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracionSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRechazo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UsuarioAprobadorId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EjemplarId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaExpiracionSolicitud");

                    b.HasIndex("UsuarioAprobadorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudesPrestamo", "prestamos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", "seguridad");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumeroEmpleado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Matricula");

                    b.HasIndex("NumeroEmpleado");

                    b.ToTable("Usuarios", "seguridad");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Seguridad.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("UsuariosRoles", "seguridad");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Auditoria.RegistroAuditoria", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Ejemplar", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.RecursoBibliografico", "RecursoBibliografico")
                        .WithMany("Ejemplares")
                        .HasForeignKey("RecursoBibliograficoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecursoBibliografico");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.HistorialEstadoEjemplar", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Ejemplar", "Ejemplar")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ejemplar");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.RecursoAutor", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Autor", "Autor")
                        .WithMany("Recursos")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.RecursoBibliografico", "RecursoBibliografico")
                        .WithMany("Autores")
                        .HasForeignKey("RecursoBibliograficoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("RecursoBibliografico");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.RecursoCategoria", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Categoria", "Categoria")
                        .WithMany("Recursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.RecursoBibliografico", "RecursoBibliografico")
                        .WithMany("Categorias")
                        .HasForeignKey("RecursoBibliograficoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("RecursoBibliografico");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Notificaciones.Notificacion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioDestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Penalizaciones.IncidenciaEjemplar", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Ejemplar", null)
                        .WithMany()
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Prestamos.Prestamo", null)
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioReportaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Penalizaciones.Penalizacion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Prestamos.Prestamo", null)
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioResolutorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.Devolucion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Prestamos.Prestamo", "Prestamo")
                        .WithMany("Devoluciones")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioBibliotecarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.Prestamo", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Ejemplar", null)
                        .WithMany()
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Prestamos.SolicitudPrestamo", null)
                        .WithMany()
                        .HasForeignKey("SolicitudPrestamoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioBibliotecarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.ReservaTemporal", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Ejemplar", null)
                        .WithMany()
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Prestamos.SolicitudPrestamo", null)
                        .WithMany()
                        .HasForeignKey("SolicitudPrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.SolicitudPrestamo", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Catalogo.Ejemplar", null)
                        .WithMany()
                        .HasForeignKey("EjemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioAprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Seguridad.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Autor", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Categoria", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.Ejemplar", b =>
                {
                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Catalogo.RecursoBibliografico", b =>
                {
                    b.Navigation("Autores");

                    b.Navigation("Categorias");

                    b.Navigation("Ejemplares");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamos.Prestamo", b =>
                {
                    b.Navigation("Devoluciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
